from __future__ import annotations

from app.domain.language import LanguageCode


DEMO_COLLECTIONS = [
    {
        "id": 1,
        "slug": "signature-essentials",
        "hero_image_url": "https://example.test/assets/collections/signature-essentials-hero.png",
        "cover_image_url": "https://example.test/assets/collections/signature-essentials-cover.png",
        "sort_order": 1,
        "is_featured": True,
        "name_translations": {
            "en": "Signature Essentials",
            "ru": "Фирменная база",
            "kk": "Негізгі капсула",
        },
        "summary_translations": {
            "en": "Monochrome building blocks cut for quiet authority.",
            "ru": "Монохромная база для строгой выразительности.",
            "kk": "Тыныш беделі бар монохром капсула.",
        },
        "eyebrow_translations": {
            "en": "Collection 01",
            "ru": "Коллекция 01",
            "kk": "Жинақ 01",
        },
    },
    {
        "id": 2,
        "slug": "city-tailoring",
        "hero_image_url": "https://example.test/assets/collections/city-tailoring-hero.png",
        "cover_image_url": "https://example.test/assets/collections/city-tailoring-cover.png",
        "sort_order": 2,
        "is_featured": True,
        "name_translations": {
            "en": "City Tailoring",
            "ru": "Городской крой",
            "kk": "Қалалық пішім",
        },
        "summary_translations": {
            "en": "Trousers and skirts designed for severe urban proportion.",
            "ru": "Брюки и юбки для строгой городской пропорции.",
            "kk": "Қалалық айқын пропорцияға арналған шалбар мен белдемше.",
        },
        "eyebrow_translations": {
            "en": "Collection 02",
            "ru": "Коллекция 02",
            "kk": "Жинақ 02",
        },
    },
    {
        "id": 3,
        "slug": "noir-volume",
        "hero_image_url": "https://example.test/assets/collections/noir-volume-hero.png",
        "cover_image_url": "https://example.test/assets/collections/noir-volume-cover.png",
        "sort_order": 3,
        "is_featured": True,
        "name_translations": {
            "en": "Noir Volume",
            "ru": "Черный объем",
            "kk": "Қара көлем",
        },
        "summary_translations": {
            "en": "Outerwear and layers with precise architectural volume.",
            "ru": "Верхняя одежда и слои с архитектурным объемом.",
            "kk": "Архитектуралық көлемі бар сырт киім мен қабаттар.",
        },
        "eyebrow_translations": {
            "en": "Collection 03",
            "ru": "Коллекция 03",
            "kk": "Жинақ 03",
        },
    },
]


DEMO_PRODUCTS = [
    {
        "id": 1,
        "sku": "TOP-001",
        "slug": "silk-shell-top",
        "name": "Silk Shell Top",
        "display_category": "База",
        "normalized_category": "top",
        "season_tags": ["spring", "summer"],
        "color": "white",
        "subtitle": "Cut close with a clean editorial line.",
        "long_description": "A sharp silk layer built for monochrome tailoring and long editorial silhouettes.",
        "base_price_minor": 24000,
        "currency": "USD",
        "collection_slug": "signature-essentials",
        "hero_image_url": "https://example.test/assets/products/top-001-hero.png",
        "gallery_image_urls": [
            "https://example.test/assets/products/top-001-1.png",
            "https://example.test/assets/products/top-001-2.png",
        ],
        "fabric_notes": "18 momme silk with a dry, matte finish.",
        "care_notes": "Dry clean only. Steam lightly between wears.",
        "preorder_note": "Made to order in a limited monochrome run.",
        "available_sizes": ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL", "6XL"],
        "size_chart_id": 1,
        "editorial_rank": 1,
        "is_featured": True,
        "reference_image_url": "https://example.test/assets/products/top-001.png",
        "is_available": True,
        "is_active": True,
        "translations": [
            {
                "language_code": LanguageCode.RU.value,
                "name": "Шелковый топ",
                "description": "Легкий шелковый топ с сухим матовым блеском.",
                "subtitle": "Чистая линия для строгой многослойности.",
                "long_description": "Шелковый топ, созданный для монохромных комплектов и выверенного силуэта.",
                "fabric_notes": "Шелк 18 momme с матовой фактурой.",
                "care_notes": "Только химчистка. Легкое отпаривание по необходимости.",
                "preorder_note": "Модель отшивается ограниченным тиражом по предзаказу.",
                "display_category": "База",
            },
            {
                "language_code": LanguageCode.KK.value,
                "name": "Жібек топ",
                "description": "Жеңіл жібек топ жұмсақ жылтырмен.",
                "subtitle": "Айқын сызық пен жинақы қабаттау үшін.",
                "long_description": "Монохром капсулаға арналған таза пішінді жібек топ.",
                "fabric_notes": "Күңгірт фактуралы 18 momme жібек.",
                "care_notes": "Тек химиялық тазалау. Қажет кезде жеңіл булау.",
                "preorder_note": "Шектеулі санмен алдын ала тапсырыс арқылы тігіледі.",
                "display_category": "Негізгі киім",
            },
            {
                "language_code": LanguageCode.EN.value,
                "name": "Silk Shell Top",
                "description": "Lightweight silk top with a soft sheen.",
                "subtitle": "Cut close with a clean editorial line.",
                "long_description": "A sharp silk layer built for monochrome tailoring and long editorial silhouettes.",
                "fabric_notes": "18 momme silk with a dry, matte finish.",
                "care_notes": "Dry clean only. Steam lightly between wears.",
                "preorder_note": "Made to order in a limited monochrome run.",
                "display_category": "Basics",
            },
        ],
    },
    {
        "id": 2,
        "sku": "BOT-001",
        "slug": "tailored-trousers",
        "name": "Tailored Trousers",
        "display_category": "Брюки",
        "normalized_category": "bottom",
        "season_tags": ["spring", "summer"],
        "color": "gray",
        "subtitle": "Long line tailoring without visual noise.",
        "long_description": "Straight, elongated trousers with a calm waist and clean fall over the shoe.",
        "base_price_minor": 32000,
        "currency": "USD",
        "collection_slug": "city-tailoring",
        "hero_image_url": "https://example.test/assets/products/bot-001-hero.png",
        "gallery_image_urls": [
            "https://example.test/assets/products/bot-001-1.png",
            "https://example.test/assets/products/bot-001-2.png",
        ],
        "fabric_notes": "Structured wool blend with fluid drape.",
        "care_notes": "Dry clean or cold hand wash only.",
        "preorder_note": "Cut after confirmation to preserve line precision.",
        "available_sizes": ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL", "6XL"],
        "size_chart_id": 1,
        "editorial_rank": 3,
        "is_featured": True,
        "reference_image_url": "https://example.test/assets/products/bot-001.png",
        "is_available": True,
        "is_active": True,
        "translations": [
            {
                "language_code": LanguageCode.RU.value,
                "name": "Брюки с защипами",
                "description": "Прямые брюки для строгих городских образов.",
                "subtitle": "Длинная линия без лишних деталей.",
                "long_description": "Брюки с чистой посадкой на талии и мягким падением по длине.",
                "fabric_notes": "Структурная шерстяная смесовая ткань.",
                "care_notes": "Химчистка или только холодная ручная стирка.",
                "preorder_note": "Кроятся после подтверждения заказа.",
                "display_category": "Брюки",
            },
            {
                "language_code": LanguageCode.KK.value,
                "name": "Бүктемелі шалбар",
                "description": "Қалалық жинақы образдарға арналған тік пішімді шалбар.",
                "subtitle": "Артық детальсыз ұзын силуэт.",
                "long_description": "Бел сызығы тыныш, пішіні таза, ұзындығы созылған шалбар.",
                "fabric_notes": "Пішінін ұстайтын жүн қоспасы.",
                "care_notes": "Тек химиялық тазалау немесе салқын қолмен жуу.",
                "preorder_note": "Тапсырыс расталғаннан кейін пішіледі.",
                "display_category": "Шалбар",
            },
            {
                "language_code": LanguageCode.EN.value,
                "name": "Tailored Trousers",
                "description": "Straight-leg trousers for polished everyday looks.",
                "subtitle": "Long line tailoring without visual noise.",
                "long_description": "Straight, elongated trousers with a calm waist and clean fall over the shoe.",
                "fabric_notes": "Structured wool blend with fluid drape.",
                "care_notes": "Dry clean or cold hand wash only.",
                "preorder_note": "Cut after confirmation to preserve line precision.",
                "display_category": "Trousers",
            },
        ],
    },
    {
        "id": 3,
        "sku": "OUT-001",
        "slug": "minimal-trench",
        "name": "Minimal Trench",
        "display_category": "Верхняя одежда",
        "normalized_category": "outerwear",
        "season_tags": ["spring", "autumn"],
        "color": "gray",
        "subtitle": "Architectural outerwear with disciplined volume.",
        "long_description": "A precise trench cut to frame layered looks without losing movement.",
        "base_price_minor": 68000,
        "currency": "USD",
        "collection_slug": "noir-volume",
        "hero_image_url": "https://example.test/assets/products/out-001-hero.png",
        "gallery_image_urls": [
            "https://example.test/assets/products/out-001-1.png",
            "https://example.test/assets/products/out-001-2.png",
        ],
        "fabric_notes": "Dense technical cotton with fluid structure.",
        "care_notes": "Professional clean recommended.",
        "preorder_note": "Outerwear pieces carry the longest delivery lead time.",
        "available_sizes": ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL", "6XL"],
        "size_chart_id": 1,
        "editorial_rank": 2,
        "is_featured": True,
        "reference_image_url": "https://example.test/assets/products/out-001.png",
        "is_available": True,
        "is_active": True,
        "translations": [
            {
                "language_code": LanguageCode.RU.value,
                "name": "Минималистичный тренч",
                "description": "Легкий плащ для межсезонной многослойности.",
                "subtitle": "Архитектурный объем без лишнего шума.",
                "long_description": "Тренч с точной линией плеча и чистым падением ткани вокруг силуэта.",
                "fabric_notes": "Плотный технический хлопок.",
                "care_notes": "Рекомендуется профессиональная чистка.",
                "preorder_note": "Верхняя одежда требует самого длинного цикла пошива.",
                "display_category": "Верхняя одежда",
            },
            {
                "language_code": LanguageCode.KK.value,
                "name": "Минимал тренч",
                "description": "Маусымаралық қабаттауға арналған жеңіл плащ.",
                "subtitle": "Архитектуралық көлем, тыныш пластика.",
                "long_description": "Иық сызығы анық, қозғалысы еркін тренч.",
                "fabric_notes": "Құрылымды техникалық мақта.",
                "care_notes": "Кәсіби тазалау ұсынылады.",
                "preorder_note": "Сырт киімнің дайындау мерзімі ұзағырақ.",
                "display_category": "Сырт киім",
            },
            {
                "language_code": LanguageCode.EN.value,
                "name": "Minimal Trench",
                "description": "Lightweight trench for transitional layered outfits.",
                "subtitle": "Architectural outerwear with disciplined volume.",
                "long_description": "A precise trench cut to frame layered looks without losing movement.",
                "fabric_notes": "Dense technical cotton with fluid structure.",
                "care_notes": "Professional clean recommended.",
                "preorder_note": "Outerwear pieces carry the longest delivery lead time.",
                "display_category": "Outerwear",
            },
        ],
    },
    {
        "id": 4,
        "sku": "TOP-002",
        "slug": "soft-cardigan",
        "name": "Soft Cardigan",
        "display_category": "Кардиганы",
        "normalized_category": "top",
        "season_tags": ["autumn", "winter"],
        "color": "black",
        "subtitle": "Weightless softness against a severe line.",
        "long_description": "A dark knit layer designed to soften tailored trousers and skirts without losing structure.",
        "base_price_minor": 29000,
        "currency": "USD",
        "collection_slug": "signature-essentials",
        "hero_image_url": "https://example.test/assets/products/top-002-hero.png",
        "gallery_image_urls": [
            "https://example.test/assets/products/top-002-1.png",
            "https://example.test/assets/products/top-002-2.png",
        ],
        "fabric_notes": "Fine-gauge knit with soft recovery.",
        "care_notes": "Cold hand wash flat dry.",
        "preorder_note": "Knits are reserved in small batch yarn runs.",
        "available_sizes": ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL", "6XL"],
        "size_chart_id": 1,
        "editorial_rank": 4,
        "is_featured": False,
        "reference_image_url": "https://example.test/assets/products/top-002.png",
        "is_available": True,
        "is_active": True,
        "translations": [
            {
                "language_code": LanguageCode.RU.value,
                "name": "Мягкий кардиган",
                "description": "Спокойный кардиган для прохладных утренних слоев.",
                "subtitle": "Мягкость внутри строгого силуэта.",
                "long_description": "Темный трикотажный слой, уравновешивающий строгие брюки и юбки.",
                "fabric_notes": "Тонкий трикотаж с мягким восстановлением формы.",
                "care_notes": "Холодная ручная стирка, сушить горизонтально.",
                "preorder_note": "Трикотаж производится малыми тиражами.",
                "display_category": "Кардиганы",
            },
            {
                "language_code": LanguageCode.KK.value,
                "name": "Жұмсақ кардиган",
                "description": "Салқын таңдарға арналған жайлы қабат.",
                "subtitle": "Қатаң силуэт ішіндегі жұмсақтық.",
                "long_description": "Шалбар мен белдемшеге тепе-теңдік беретін қара трикотаж қабаты.",
                "fabric_notes": "Пішінін жұмсақ сақтайтын жұқа трикотаж.",
                "care_notes": "Салқын қолмен жуу, жайып кептіру.",
                "preorder_note": "Трикотаж иірімі шағын партиямен шығарылады.",
                "display_category": "Кардигандар",
            },
            {
                "language_code": LanguageCode.EN.value,
                "name": "Soft Cardigan",
                "description": "Cozy cardigan for cool layered mornings.",
                "subtitle": "Weightless softness against a severe line.",
                "long_description": "A dark knit layer designed to soften tailored trousers and skirts without losing structure.",
                "fabric_notes": "Fine-gauge knit with soft recovery.",
                "care_notes": "Cold hand wash flat dry.",
                "preorder_note": "Knits are reserved in small batch yarn runs.",
                "display_category": "Cardigans",
            },
        ],
    },
    {
        "id": 5,
        "sku": "BOT-002",
        "slug": "straight-skirt",
        "name": "Straight Skirt",
        "display_category": "Юбки",
        "normalized_category": "bottom",
        "season_tags": ["summer"],
        "color": "black",
        "subtitle": "A strict column with quiet movement.",
        "long_description": "A column skirt built to sit close and hold a straight, formal proportion.",
        "base_price_minor": 26000,
        "currency": "USD",
        "collection_slug": "city-tailoring",
        "hero_image_url": "https://example.test/assets/products/bot-002-hero.png",
        "gallery_image_urls": [
            "https://example.test/assets/products/bot-002-1.png",
            "https://example.test/assets/products/bot-002-2.png",
        ],
        "fabric_notes": "Dense suiting cloth with subtle stretch.",
        "care_notes": "Dry clean only.",
        "preorder_note": "Reserved for preorder to keep inventory lean.",
        "available_sizes": ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL", "6XL"],
        "size_chart_id": 1,
        "editorial_rank": 5,
        "is_featured": False,
        "reference_image_url": "https://example.test/assets/products/bot-002.png",
        "is_available": True,
        "is_active": True,
        "translations": [
            {
                "language_code": LanguageCode.RU.value,
                "name": "Прямая юбка",
                "description": "Лаконичная юбка для строгих городских комплектов.",
                "subtitle": "Строгая колонна с мягким движением.",
                "long_description": "Юбка-колонна, удерживающая прямую и выверенную пропорцию.",
                "fabric_notes": "Плотная костюмная ткань с легкой эластичностью.",
                "care_notes": "Только химчистка.",
                "preorder_note": "Доступна по предзаказу для бережного производства.",
                "display_category": "Юбки",
            },
            {
                "language_code": LanguageCode.KK.value,
                "name": "Тік белдемше",
                "description": "Қалалық жинақы образдарға арналған белдемше.",
                "subtitle": "Тыныш қозғалысы бар тік колонна.",
                "long_description": "Пропорциясы айқын, сызығы таза белдемше-колонна.",
                "fabric_notes": "Сәл созылатын қалың костюм матасы.",
                "care_notes": "Тек химиялық тазалау.",
                "preorder_note": "Ұқыпты өндіріс үшін алдын ала тапсырыспен ұсынылады.",
                "display_category": "Белдемше",
            },
            {
                "language_code": LanguageCode.EN.value,
                "name": "Straight Skirt",
                "description": "Clean-lined skirt for structured city dressing.",
                "subtitle": "A strict column with quiet movement.",
                "long_description": "A column skirt built to sit close and hold a straight, formal proportion.",
                "fabric_notes": "Dense suiting cloth with subtle stretch.",
                "care_notes": "Dry clean only.",
                "preorder_note": "Reserved for preorder to keep inventory lean.",
                "display_category": "Skirts",
            },
        ],
    },
]


DEMO_SIZE_CHARTS = [
    {
        "id": 1,
        "name": "AVISHU Signature Size Guide",
        "sizes": [
            {"size_label": "XS", "chest_min_cm": 80, "chest_max_cm": 85, "waist_min_cm": 60, "waist_max_cm": 65, "hips_min_cm": 88, "hips_max_cm": 93},
            {"size_label": "S", "chest_min_cm": 86, "chest_max_cm": 93, "waist_min_cm": 66, "waist_max_cm": 73, "hips_min_cm": 94, "hips_max_cm": 101},
            {"size_label": "M", "chest_min_cm": 94, "chest_max_cm": 99, "waist_min_cm": 74, "waist_max_cm": 80, "hips_min_cm": 102, "hips_max_cm": 107},
            {"size_label": "L", "chest_min_cm": 100, "chest_max_cm": 105, "waist_min_cm": 81, "waist_max_cm": 86, "hips_min_cm": 108, "hips_max_cm": 113},
            {"size_label": "XL", "chest_min_cm": 106, "chest_max_cm": 111, "waist_min_cm": 87, "waist_max_cm": 92, "hips_min_cm": 114, "hips_max_cm": 119},
            {"size_label": "2XL", "chest_min_cm": 112, "chest_max_cm": 117, "waist_min_cm": 93, "waist_max_cm": 98, "hips_min_cm": 120, "hips_max_cm": 125},
            {"size_label": "3XL", "chest_min_cm": 118, "chest_max_cm": 123, "waist_min_cm": 99, "waist_max_cm": 104, "hips_min_cm": 126, "hips_max_cm": 131},
            {"size_label": "4XL", "chest_min_cm": 124, "chest_max_cm": 129, "waist_min_cm": 105, "waist_max_cm": 110, "hips_min_cm": 132, "hips_max_cm": 137},
            {"size_label": "5XL", "chest_min_cm": 130, "chest_max_cm": 135, "waist_min_cm": 111, "waist_max_cm": 116, "hips_min_cm": 138, "hips_max_cm": 143},
            {"size_label": "6XL", "chest_min_cm": 136, "chest_max_cm": 141, "waist_min_cm": 117, "waist_max_cm": 122, "hips_min_cm": 144, "hips_max_cm": 149},
        ],
    }
]
